version: "3"

services:
  node:
    container_name: node-server
    restart: always
    build: ./server
    ports:
      - "8080:8080"
  react:
    container_name: react-app
    build: ./client
    ports:
      - "8081:8081"
